name: EssentialsCAPITest
version: '${project.version}'
main: net.godlycow.org.api.test.Main
api-version: '1.21'
depend: [EssentialsC]

commands:
  tkit:
    description: Test the EssentialsC Kit API
    usage: /tkit <subcommand>
