<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>net.godlycow.org</groupId>
        <artifactId>EssentialsC-parent</artifactId>
        <version>4.1.3</version>
    </parent>

    <artifactId>EssentialsC-aggregator</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>essc</module>
        <module>test-api</module>
    </modules>

    <profiles>
        <profile>
            <id>run-server</id>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>3.1.0</version>

                        <executions>
                            <execution>
                                <id>start-server</id>
                                <phase>install</phase>

                                <goals>
                                    <goal>run</goal>
                                </goals>

                                <configuration>
                                    <target>

                                        <echo message="Starting Purpur dev server..."/>

                                        <exec executable="java"
                                              dir="${project.basedir}/../run-server"
                                              failonerror="true">

                                            <arg value="-Xms1G"/>
                                            <arg value="-Xmx1G"/>
                                            <arg value="-jar"/>
                                            <arg value="purpur-1.21.11-2559.jar"/>
                                            <arg value="nogui"/>

                                        </exec>

                                    </target>
                                </configuration>

                            </execution>
                        </executions>

                    </plugin>
                </plugins>
            </build>

        </profile>
    </profiles>

</project>